create sequence hibernate_sequence start 1 increment 1
create table books (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, primary key (id))
create table customers (id int8 not null, firstname varchar(255), lastname varchar(255), primary key (id))
create table games (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, primary key (id))
create table lps (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, primary key (id))
create table orders (id  bigserial not null, primary key (id))
create table reviews (id  bigserial not null, primary key (id))
alter table books add constraint UK_nnb0smwlcavaglkn5v3tl3dvr unique (price)
alter table books add constraint UK_5mtto2jcmfrwfg0p1ui8mnweu unique (title)
alter table games add constraint UK_pyguyublvqe32jpmyf4j9g2kp unique (price)
alter table games add constraint UK_7gkxklsyushpm5uqe78dm4nwi unique (title)
alter table lps add constraint UK_nn6n3bp6qss21weoron9036e6 unique (price)
alter table lps add constraint UK_cabu3db4werug4x6c9us8ny45 unique (title)
create sequence hibernate_sequence start 1 increment 1
create table books (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, author varchar(100), isbn varchar(255) not null, pages int8, primary key (id))
create table customers (id int8 not null, firstname varchar(255), lastname varchar(255), primary key (id))
create table games (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, genre varchar(255), min_age int8, publisher varchar(100), primary key (id))
create table lps (id  bigserial not null, price numeric(19, 2) not null, supplier_id varchar(100) not null, title varchar(100) not null, artist varchar(100) not null, genre varchar(255), primary key (id))
create table orders (id  bigserial not null, primary key (id))
create table reviews (id  bigserial not null, primary key (id))
alter table books add constraint books_unique unique (isbn)
